sudo: required
dist: trusty
language: ruby
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install: gem install bundler -v 1.13.6
